/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package Matriculacion;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Administrador
 */
public class FormularioMatriculacion extends javax.swing.JFrame {

    /**
     * Creates new form FormularioMatriculacion
     */
    public FormularioMatriculacion() {
        initComponents();
        setLocationRelativeTo(null);//centra la ventana en la patalla
        setTitle("Matriculacion");
        setVisible(true); 
        Error.setVisible(false);
        Error2.setVisible(false);
        
       
    }
    //int numeroAchivos=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClaroOsucrobuttonGroup = new javax.swing.ButtonGroup();
        TamañoLetrabuttonGroup = new javax.swing.ButtonGroup();
        fondo = new javax.swing.JPanel();
        Ingreso = new javax.swing.JLabel();
        curso = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        alumno = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        distrito = new javax.swing.JLabel();
        CursoTextField = new javax.swing.JTextField();
        AlumnoTextField = new javax.swing.JTextField();
        DireccionTextField = new javax.swing.JTextField();
        DistritoTextField = new javax.swing.JTextField();
        FechaSpinner = new javax.swing.JSpinner();
        SexoComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        GuardarButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DistritosTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        CursosTable = new javax.swing.JTable();
        Error = new javax.swing.JLabel();
        Error2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ClaroRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        OscuroRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        DoceRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        CatorceRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        DieciseisRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ingreso.setText("Ingreso de datos");

        curso.setText("Curso");

        fecha.setText("Fecha");

        alumno.setText("Alumno");

        sexo.setText("Sexo");

        direccion.setText("Direccion");

        distrito.setText("Distrito");

        CursoTextField.setEditable(false);
        CursoTextField.setPreferredSize(new java.awt.Dimension(140, 22));

        AlumnoTextField.setPreferredSize(new java.awt.Dimension(140, 22));

        DireccionTextField.setPreferredSize(new java.awt.Dimension(140, 22));

        DistritoTextField.setEditable(false);
        DistritoTextField.setPreferredSize(new java.awt.Dimension(140, 22));
        DistritoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistritoTextFieldActionPerformed(evt);
            }
        });

        FechaSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.YEAR));
        FechaSpinner.setToolTipText("");
        FechaSpinner.setPreferredSize(new java.awt.Dimension(140, 22));

        SexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra", "porfavorygracias" }));
        SexoComboBox.setPreferredSize(new java.awt.Dimension(140, 22));

        jLabel8.setText("Opciones");

        GuardarButton.setText("Guardar");
        GuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarButtonActionPerformed(evt);
            }
        });

        SalirButton.setText("Salir");
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        DistritosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Telde"},
                {"Las palmas"},
                {"Arucas"},
                {"Agüimes"},
                {"Santa brigida"},
                {"Ingenio"},
                {"Murcia"},
                {"Caracas"},
                {"Moscu"},
                {null}
            },
            new String [] {
                "Distritos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DistritosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DistritosTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(DistritosTable);

        CursosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Phyton"},
                {"Java"},
                {"Bachata intesa"},
                {"Cocina"},
                {"Danza Taitiana"},
                {"Peluqueria"},
                {"Carpinteria"},
                {"Zapateria"},
                {"Sarteria"},
                {"Monopoli competitivo"},
                {"Parchis"}
            },
            new String [] {
                "Cursos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CursosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CursosTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(CursosTable);

        Error.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Error.setForeground(new java.awt.Color(255, 51, 51));
        Error.setText("*");

        Error2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Error2.setForeground(new java.awt.Color(255, 51, 51));
        Error2.setText("*");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(Ingreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(GuardarButton)
                            .addComponent(SalirButton))
                        .addGap(104, 104, 104))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(curso)
                                    .addComponent(fecha))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alumno)
                                    .addComponent(sexo)
                                    .addComponent(direccion)
                                    .addComponent(distrito))
                                .addGap(18, 18, 18)))
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(CursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DireccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DistritoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(AlumnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Error2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingreso)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curso)
                    .addComponent(CursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarButton)
                    .addComponent(Error))
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fecha)
                            .addComponent(FechaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alumno)
                            .addComponent(AlumnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Error2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexo)
                            .addComponent(SexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(SalirButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion)
                    .addComponent(DireccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distrito)
                    .addComponent(DistritoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jMenu1.setText("Temas");

        ClaroOsucrobuttonGroup.add(ClaroRadioButtonMenuItem);
        ClaroRadioButtonMenuItem.setSelected(true);
        ClaroRadioButtonMenuItem.setText("Claro");
        ClaroRadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaroRadioButtonMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ClaroRadioButtonMenuItem);

        ClaroOsucrobuttonGroup.add(OscuroRadioButtonMenuItem);
        OscuroRadioButtonMenuItem.setText("Oscuro");
        OscuroRadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OscuroRadioButtonMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(OscuroRadioButtonMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tamaño letra");

        TamañoLetrabuttonGroup.add(DoceRadioButtonMenuItem);
        DoceRadioButtonMenuItem.setSelected(true);
        DoceRadioButtonMenuItem.setText("12");
        DoceRadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoceRadioButtonMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(DoceRadioButtonMenuItem);

        TamañoLetrabuttonGroup.add(CatorceRadioButtonMenuItem);
        CatorceRadioButtonMenuItem.setText("14");
        CatorceRadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatorceRadioButtonMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(CatorceRadioButtonMenuItem);

        TamañoLetrabuttonGroup.add(DieciseisRadioButtonMenuItem);
        DieciseisRadioButtonMenuItem.setText("16");
        DieciseisRadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DieciseisRadioButtonMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(DieciseisRadioButtonMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DistritoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistritoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistritoTextFieldActionPerformed

    private void OscuroRadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OscuroRadioButtonMenuItemActionPerformed
        fondo.setBackground(Color.lightGray);
        
        
    }//GEN-LAST:event_OscuroRadioButtonMenuItemActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
     System.exit(0);
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void GuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarButtonActionPerformed
        Creararchivo();       
    }//GEN-LAST:event_GuardarButtonActionPerformed
    //rellena curso con lo que este seleccionado en la tabla
    private void CursosTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CursosTableMousePressed
        String contenido=(String) CursosTable.getValueAt(CursosTable.getSelectedRow(), 0);
        CursoTextField.setText(contenido);
    }//GEN-LAST:event_CursosTableMousePressed
    //distrito curso con lo que este seleccionado en la tabla
    private void DistritosTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DistritosTableMousePressed
        String contenido=(String) DistritosTable.getValueAt(DistritosTable.getSelectedRow(), 0);
        DistritoTextField.setText(contenido);
    }//GEN-LAST:event_DistritosTableMousePressed
    //cambia el fondo de color
    private void ClaroRadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaroRadioButtonMenuItemActionPerformed
        fondo.setBackground(Color.white);
    }//GEN-LAST:event_ClaroRadioButtonMenuItemActionPerformed
    //cambia el tamaño de la letra
    private void DoceRadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoceRadioButtonMenuItemActionPerformed
        Ingreso.setFont(new Font(Ingreso.getFont().getFontName(), Ingreso.getFont().getStyle(),12)); 
        curso.setFont(new Font(curso.getFont().getFontName(), curso.getFont().getStyle(),12)); 
        fecha.setFont(new Font(fecha.getFont().getFontName(), fecha.getFont().getStyle(),12)); 
        alumno.setFont(new Font(alumno.getFont().getFontName(), alumno.getFont().getStyle(),12)); 
        sexo.setFont(new Font(sexo.getFont().getFontName(), Ingreso.getFont().getStyle(),12)); 
        direccion.setFont(new Font(direccion.getFont().getFontName(), direccion.getFont().getStyle(),12)); 
        distrito.setFont(new Font(distrito.getFont().getFontName(), distrito.getFont().getStyle(),12)); 
    }//GEN-LAST:event_DoceRadioButtonMenuItemActionPerformed
    //cambia el tamaño de la letra
    private void CatorceRadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatorceRadioButtonMenuItemActionPerformed
       Ingreso.setFont(new Font(Ingreso.getFont().getFontName(), Ingreso.getFont().getStyle(),14)); 
        curso.setFont(new Font(curso.getFont().getFontName(), curso.getFont().getStyle(),14)); 
        fecha.setFont(new Font(fecha.getFont().getFontName(), fecha.getFont().getStyle(),14)); 
        alumno.setFont(new Font(alumno.getFont().getFontName(), alumno.getFont().getStyle(),14)); 
        sexo.setFont(new Font(sexo.getFont().getFontName(), Ingreso.getFont().getStyle(),14)); 
        direccion.setFont(new Font(direccion.getFont().getFontName(), direccion.getFont().getStyle(),14)); 
        distrito.setFont(new Font(distrito.getFont().getFontName(), distrito.getFont().getStyle(),14)); 
    }//GEN-LAST:event_CatorceRadioButtonMenuItemActionPerformed
    //cambia el tamaño de la letra
    private void DieciseisRadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DieciseisRadioButtonMenuItemActionPerformed
        Ingreso.setFont(new Font(Ingreso.getFont().getFontName(), Ingreso.getFont().getStyle(),16)); 
         curso.setFont(new Font(curso.getFont().getFontName(), curso.getFont().getStyle(),16)); 
        fecha.setFont(new Font(fecha.getFont().getFontName(), fecha.getFont().getStyle(),16)); 
        alumno.setFont(new Font(alumno.getFont().getFontName(), alumno.getFont().getStyle(),16)); 
        sexo.setFont(new Font(sexo.getFont().getFontName(), Ingreso.getFont().getStyle(),16)); 
        direccion.setFont(new Font(direccion.getFont().getFontName(), direccion.getFont().getStyle(),16)); 
        distrito.setFont(new Font(distrito.getFont().getFontName(), distrito.getFont().getStyle(),16)); 
    }//GEN-LAST:event_DieciseisRadioButtonMenuItemActionPerformed

    public void Creararchivo(){
        
        //numeroAchivos++;
         // Especifica la ruta y el nombre del archivo
        String rutaArchivo = "C:\\Users\\Administrador\\Documents\\NetBeansProjects\\Matriculacion\\Matriculas\\";
        String nombreArchivo= CursoTextField.getText() + AlumnoTextField.getText();
        
        String Arhivo= rutaArchivo + nombreArchivo +".txt";
        if(!CursoTextField.getText().isEmpty()&&!AlumnoTextField.getText().isEmpty()){
             Error.setVisible(false);
             Error2.setVisible(false);
            
             try {
            // Crea un objeto File para representar el archivo
            File archivo = new File(Arhivo);

            // Verifica si el archivo ya existe
            if (archivo.createNewFile()) {
                System.out.println("Archivo creado con éxito: " + archivo.getName());
            } else {
                System.out.println("El archivo ya existe.");
            }

            
            // Ahora, puedes escribir contenido en el archivo usando FileWriter
            String contenidoArchivo=CursoTextField.getText()+";"+ FechaSpinner.getValue()+";" + AlumnoTextField.getText()+";"+SexoComboBox.getSelectedItem()+";"+DireccionTextField.getText()+";"+DistritoTextField.getText();
            FileWriter escritor = new FileWriter(archivo);
            escritor.write(contenidoArchivo);
            escritor.close();

            System.out.println("Contenido escrito en el archivo.");

        } catch (IOException e) {
            System.err.println("Error al crear o escribir en el archivo: " + e.getMessage());
        }
            
            
        }else{
             Error.setVisible(true);
            Error2.setVisible(true);
        }
       
       
    }
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioMatriculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioMatriculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioMatriculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioMatriculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioMatriculacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlumnoTextField;
    private javax.swing.JRadioButtonMenuItem CatorceRadioButtonMenuItem;
    private javax.swing.ButtonGroup ClaroOsucrobuttonGroup;
    private javax.swing.JRadioButtonMenuItem ClaroRadioButtonMenuItem;
    private javax.swing.JTextField CursoTextField;
    private javax.swing.JTable CursosTable;
    private javax.swing.JRadioButtonMenuItem DieciseisRadioButtonMenuItem;
    private javax.swing.JTextField DireccionTextField;
    private javax.swing.JTextField DistritoTextField;
    private javax.swing.JTable DistritosTable;
    private javax.swing.JRadioButtonMenuItem DoceRadioButtonMenuItem;
    private javax.swing.JLabel Error;
    private javax.swing.JLabel Error2;
    private javax.swing.JSpinner FechaSpinner;
    private javax.swing.JButton GuardarButton;
    private javax.swing.JLabel Ingreso;
    private javax.swing.JRadioButtonMenuItem OscuroRadioButtonMenuItem;
    private javax.swing.JButton SalirButton;
    private javax.swing.JComboBox<String> SexoComboBox;
    private javax.swing.ButtonGroup TamañoLetrabuttonGroup;
    private javax.swing.JLabel alumno;
    private javax.swing.JLabel curso;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel distrito;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel sexo;
    // End of variables declaration//GEN-END:variables
}
